#
# simInt simRMLVelocity(simInt dofs,simDouble timeStep,const simDouble* currentPosVelAccel,const simDouble* maxAccelJerk,const simBool* selection,const simDouble* targetVel,simDouble* newPosVelAccel)
#

int32 dofs
float64 timeStep
int32 flags
float64[] currentPosVelAccel
float64[] maxAccelJerk
uint8[] selection
float64[] targetVel
---
int32 result
float64[] newPosVelAccel
